### PR TITLE
add: CI to the project

### LINKED ISSUE #2: add support for CI testing on every push to the codebase
**Is your feature request related to a problem? Please describe.**
Currently, the project does not have support to test whether the code it contains will successfully run or not. That might lead to exposure to potential human-prone issues.

**Describe the solution you'd like**
Add TravisCI/CircleCI or in general, any CI's testinig support so that, every push will only succeed when the code corresponding to the push passes a certain of tests successfully.

**Describe alternatives you've considered**
NA

**Additional context**
NA.

### PR DESCRIPTION
**Pull request by DarthBenro008**
Fixes #2 

- installs dependencies
- activates on all PRs and Pushes made to master branch
- does lint before testing
- added a simple sample test script

### CODE REVIEW

**Comment by DarthBenro008** [comment]
@yashvardhan-kukreja i just fixed a merge conflict and resolved the issues, i have written a Github Action that triggers on any PR or push to master branch.

**Comment by yashvardhan-kukreja** [comment]
Fantastic work!
Some hrs ago I just merged a PR which already added some unit tests.

So, i believe now that we dont specifically need the example tests. So, you can rebase the changes from master branch and use those unit tests for testing instead.

And please feel free to add more unit tests to it if you want :)

**Comment by DarthBenro008** [comment]
@yashvardhan-kukreja in my latest conflict resolve, i have utilised those unit tests that you had merged. So the this PR also contains those tests.

**Comment by yashvardhan-kukreja** [comment]
yep, sorted then but I believe that we can still get rid of the example tests. They don't seem to adding any functional coverage to the test suite.

**Comment by DarthBenro008** [comment]
@yashvardhan-kukreja removed example tests  👍

**Comment by yashvardhan-kukreja** [comment]
lgtm. Thanks for the contribution :)

**Pull request merged**
