### PR TITLE
Clone with HTTPS instead of SSH in Project Setup

### PR DESCRIPTION
**Pull request by dafiulh**
I wanted to contribute to this repository by adding some facts. So I followed the steps in the project setup section of README, and immediately found the problem in the first step. I run this command on my computer:
```sh
git clone git@github.com:yashvardhan-kukreja/nail-hacktoberfest.git
```
And then it failed ...
```
Cloning into 'nail-hacktoberfest'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I think that's because the repository given in the argument is SSH, which as far as I know it can only be used when you have SSH keys for that repository (correct my if I'm wrong). So I changed it to HTTPS, and it worked!

### CODE REVIEW

**Comment by yashvardhan-kukreja** [comment]
Nice catch. 
But the actual reason to this is different.
For using the SSH endpoint to clone repos, you have to setup github ssh keys on your account and git. 
Then, you would be able to clone any public repo (eveb this) with that.

But great job highlighting this out because new comers won't have github ssh keys configured anyways so this issue might turn them off. 

So, what I'd suggest is for you to make another commit to involve both the endpoints instead of just the https endpoint.

something like

**- <https endpoint>
OR, if you want to clone with adventure then,
- <ssh endpoint> (if you have setup ssh keys**)

you can avoid the second line if it sounds cringey though.😂

**Comment by dafiulh** [comment]
Done :smile:

**Comment by yashvardhan-kukreja** [comment]
lgtm. Merging :)

**Comment by dafiulh** [comment]
sure :+1:

**Pull request merged**
