### PR TITLE
Unit testing

### PR DESCRIPTION
**Pull request by LuisEGR**
I've added the requested unit testing, and also changed a little bit the implementation, so we don't have to test directly the index.js in the bin folder, but the app module which contains the module which consist in only one function.

Unit testing done with Jest

run with:
`npm run test`

if we get the coverage is always 50% branches for the /src/index.js since there is not fact with author, I was going to add one, but didn't find it.

### CODE REVIEW

**Comment by LuisEGR** [comment]
#15

**Comment by LuisEGR** [comment]
#3

**Comment by yashvardhan-kukreja** [comment]
Fantastic :D 
Please resolve the conflicts, rest seems great 😄

**Comment by LuisEGR** [comment]
Merge solved, and also the lint :)

**Comment by yashvardhan-kukreja** [comment]
Fantastic! 😄 
another small conflict is happening (thanks to the flooding PRs on this repo 👀)
please resolve it, then it's gonna be all in for a merge 🚀

**Comment by LuisEGR** [comment]
You should be more careful when accepting pull request, clearly you are not used to, you just accepted the Lint validator, but all the lint was wrong, they should correct it, so I didn't have to, and now you accepted some broken array and it's again me which have to fix it, if you are not careful when merging this kind of thing nobody will want to collaborate with your open source projects anymore.

**Comment by yashvardhan-kukreja** [comment]
cool. Will keep this in mind. Thanks for the suggestion :)

**Pull request merged**
